### ISSUE TITLE
SD1.5/2.1 pipeline

### ISSUE THREAD

**Issue by SuperStacie** [PRIS-CV/DemoFusion#18]
Hi,
Thanks for the great work! 
I wonder if you are planning to release the pipeline_demofusion_sd1.5/2.1. Will the generation will be much faster?

**Comment by RuoyiDu** [comment]
Hi @SuperStacie, 1.5/2.1 does work faster than XL, but this is mainly because of their lower resolution. 

The same high resolution image, say 2048*2048, is 2x upscaling for SDXL, but 4x upscaling for SD1.5. This doesn't result in higher efficiency, only lower performance. So I still recommend SDXL as the optimal choice.
