### ISSUE TITLE
Some test cannot obtain good performance

### ISSUE THREAD

**Issue by zzzzzuber** [PRIS-CV/DemoFusion#29]
Thanks for your work, it's very inspration and interesting!!!
However, I tried text2img and demofusion + controlnet pipelines, but i cannot obtain very clear and sharp results.
Some generate images have grid texture, and they are grid and blury.
i don't know if i do something wrong, thanks for your help!!!!!!!!
**Here are some results about controlnet:**
image_0,1,2 means different phase
![controlnet-demofusion](https://github.com/PRIS-CV/DemoFusion/assets/30710152/ce91d0e7-14f9-4fde-a744-bb74add81aaf)
My parameters(same as paper):
    prompt = ""
    negative_prompt = ""
    controlnet_conditioning_scale = 0.5
    height=3072
    width=3072
    num_inference_steps = 50
    guidance_scale = 7.5
    cosine_scale_1 = 3
    cosine_scale_2 = 1
    cosine_scale_3 = 1
    sigma = 0.8
    view_batch_size = 16
    stride = 64
    seed = 1
**Here are some results about text2img:**
![image](https://github.com/PRIS-CV/DemoFusion/assets/30710152/c1b901a3-4f0e-43b3-bafb-9d6c31aca5b5)
Parameters:
prompt = "The image features a large building with a prominent advertisement on its side. The advertisement showcases a woman wearing a red dress, and she is holding a bottle of perfume. The building's facade is adorned with a large sign that reads \"BONA.\" The scene captures the attention of passersby with the eye-catching advertisement and the building's distinctive design."
pipe(prompt, negative_prompt=negative_prompt,
                    height=3072, width=3072, view_batch_size=16, stride=64,
                    num_inference_steps=50, guidance_scale=7.5,
                    cosine_scale_1=3, cosine_scale_2=1, cosine_scale_3=1, sigma=0.8,
                    multi_decoder=True, show_image=False, lowvram=False
                    )

**Comment by RuoyiDu** [comment]
Hi @zzzzzuber, thanks for your interest! 

- For the DemoFusion+ControlNet Text2Image sample, I think the main problem is that you need to enter the prompt, otherwise SDXL will generate meaningless noise.
- For the DemoFusion Text2Image sample, there are no obvious problems from the parameters. This is probably a typical failure of DemoFusion, as we recently found out that it's not very good at upscaling images with visible edges (such as manga-style images) and introduces high-frequency noise. Perhaps you could try a simple prompt like "a cute dog" and see if you get good results. If so, you are using it correctly!

**Comment by zzzzzuber** [comment]
OK，I will try other prompts, thank you very much! Have a nice day~
